name: Deploy Cloudflare Worker

on:
  # Trigger deployment on push to the main branch
  push:
    branches:
      - main
  # Allow manual deployment via the GitHub UI
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose an environment to deploy to: <dev|staging|prod>"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Optional, if needed
          command: deploy
          # Optionally specify other inputs as needed
          # workingDirectory: 'path/to/your/project'  # Optional
          # wranglerVersion: '2.20.0'  # Optional, specify if you need a specific version
          # secrets: |
          #   SECRET1
          #   SECRET2  # Optional, if you have Worker secrets to set
          # preCommands: echo "*** pre command ***"  # Optional
          # postCommands: |
          #   echo "*** post commands ***"  # Optional


